common: &common
  adapter: postgresql
  username: hbs_demo
  password: hbs_demo

development:
  <<: *common
  database: hbs_demo_development

test:
  <<: *common
  database: hbs_demo_test

production:
  <<: *common
  database: hbs_demo_production